#
# INSTRUCTIONS FOR PUBLISHING TO MARKETPLACE:
#
# 1. Build a feature
#    Develop new feature and merge code into the master branch
#    of https://github.com/djnicholson/release-action.
# 3. Determine what the next version tag is going to be 
#    The current value of the "tag-name" setting (found lower 
#    down in this file will be used).
# 2. Edit README.md 
#    Change the two examples to use the next version tag.
# 3. Commit and push to GitHub
#    Wait for the Action to succeed (monitor this at 
#    https://github.com/djnicholson/release-action/actions)
# 4. Publish to the market place
#    Go to: 
#    https://github.com/djnicholson/release-action/releases
#    Edit the "Upcoming release" (check the "Publish to GitHub
#    Marketplace" box and give it a meaningful title and
#    description).
# 5. Decide what the next version number will be
#    Update the "tag-name" setting lower in this file (increment
#    the value) then commit and merge into master.
#

name: Build

on:
  push:
    branches: [ master ]

jobs:
  testaction:
    runs-on: ubuntu-latest
    name: Build TypeScript and publish to release
    steps:
      - name: ⏳ Checkout
        uses: actions/checkout@v2
      - name: 💿 Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 🚀 Build
        run: |
          npm ci
          npm run build
      - name: 🌎 Release (using local code)
        uses: ./
        id: release-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: 'v2.8'
          release-name: 'Upcoming release'
          asset-name: 'index.js'
          file: 'dist/index.js'
