name: BuildTest

on:
  pull_request:
    branches: [ master ]

jobs:
  testaction:
    runs-on: ubuntu-latest
    name: Check that code builds
    steps:
      - name: ⏳ Checkout
        uses: actions/checkout@v2
      - name: 💿 Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 🚀 Build
        run: |
          npm ci
          npm run build

